FROM rranshous/simpleagent-rpi

RUN apt-get update
RUN apt-get install -y build-essential

ADD robogachi.rb /app/robogachi.rb
ADD Gemfile /app/Gemfile-alt

RUN cat Gemfile-alt >> Gemfile
RUN bundle install

ENTRYPOINT ["bundle", "exec", "ruby", "robogachi.rb"]
